### ISSUE TITLE
Possible typo in the paper

### ISSUE THREAD

**Issue by parksw3** [adbecker/tsiR#1]
Hi, I think there is a typo in the PLOS paper:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185528

Equation 2 writes 
S_{t+1} = B_{t+1} - S_{t} - I_{t+1}
but previous literature on the TSIR model suggests that the equation should be
S_{t+1} = B_{t+1} + S_{t} - I_{t+1}.

**Comment by adbecker** [comment]
Hi @parksw3, thank you for your note. It appears you are right. Thankfully the derivation in eq (3) is correct, and the package R code does not reflect that typo. I will see if we can issue a correction. Please feel free to contact me with further questions, Best,

**Comment by adbecker** [comment]
Hi @parksw3, yes, the NULL element was a carry over from a much earlier version. I may or may not end up removing it whenever I add more data to package (hopefully soon). Best,

**Comment by adbecker** [comment]
In accordance with PLOS ONEs policy of typos / issues that do not impact results (https://journals.plos.org/plosone/s/corrections-and-retractions), I have added a comment to the MS page here: 

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185528

Thank you again,
