### ISSUE TITLE
Interested in using for NYT COVID model

### ISSUE THREAD

**Issue by jkylearmstrong** [adbecker/tsiR#2]
I came across your package in a search for a time series approach on modeling the NYT COVID data [https://github.com/nytimes/covid-19-data](https://github.com/nytimes/covid-19-data). 

After reading [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185528](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185528) I still think I have not used the `tsiRdata` function correctly. 

Ideally we would like to use `mcmcestpars` followed by `simulatetsir`, correct?

**Comment by adbecker** [comment]
Ideally you'll want to go from tsiRdata -> mcmcestpars -> simulatetsir or tsiRdata -> runtsir. Without more detail however, I'd strongly caution against using the TSIR model for COVID-19 -- the TSIR model works best on long time series data ( ~ 10 + years) where you have sufficient data to infer time-varying seasonality patterns. The model also assumes that cumulative cases is approximately equal to cumulative births which may not yet be the case with COVID-19.
