### ISSUE TITLE
Error: Either ymin or ymax must be given as an aesthetic. in plotres(LondonRes)

### ISSUE THREAD

**Issue by khorshidisamira** [adbecker/tsiR#3]
I am trying your example in the documentation and while running the following code: 
```
library(tsiR)
LondonMeas <- twentymeas[["London"]]

LondonRes <- runtsir(data=LondonMeas, IP = 2,
                     xreg = 'cumcases', regtype='gaussian',
                     alpha = NULL, sbar = NULL,family = 'gaussian', link = 'identity', method = 'negbin', nsim = 100)
plotres(LondonRes)
```
only first four plot is published and I get this error: 

> > plotres(LondonRes)
> Error: Either ymin or ymax must be given as an aesthetic.
> Run `rlang::last_error()` to see where the error occurred.
> In addition: Warning message:
> Ignoring unknown aesthetics: fill

**Comment by adbecker** [comment]
Hello, could you try re-installing the package from the github and see if the problem persists? Did you recently install the package off of CRAN? This is from a change in ggplot2 which I thought I had fixed, but perhaps not...

require(devtools)
install_github("adbecker/tsiR")

**Comment by khorshidisamira** [comment]
Hi,
I did what you said, but still I am getting the same error.

**Comment by adbecker** [comment]
What version of ggplot2 are you using? I can't produce the error on my computer using 3.3.2, so wondering if that's the issue?

packageVersion("ggplot2")
